version: "3.9"
services:
  web:
    build: .
    volumes:
      - "./:/app"

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "5000:80"
    depends_on:
      - web

  redis:
    image: "rabbitmq:3-management-alpine"
    container_name: "rabbit-mq"
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "soextreme"
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"